import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { stringify, isLosslessNumber } from 'lossless-json';
import { parse, validate } from '../src/lib/json/engine';
import { analyze } from '../src/lib/json/analysis';
import { decodeInput } from '../src/lib/json/smartInput';
import { maskJson } from '../src/lib/json/privacy';
import { repairJson } from '../src/lib/json/repair';
import { formatPath } from '../src/lib/paths';
import { branch, BRANCH_PAGE_SIZE } from '../src/lib/json/branches';
import { discoverArrays, largeGraph, largeTable } from '../src/lib/json/largeViews';
import { generateTypes } from '../src/lib/json/typeGeneration';
import { beautifyJson, minifyJson } from '../src/lib/json/transforms';

const huge = '18446744073709551615';
const input = `{"id":${huge},"decimal":1.23000,"overflow":2.3e+500,"__proto__":{"x":1},"constructor":2}`;
const value = parse(input, { lossless: true }) as Record<string, unknown>;
assert.ok(isLosslessNumber(value.id));
assert.equal(stringify(value), input);
assert.equal(Object.getPrototypeOf(value), Object.prototype);
assert.ok(Object.hasOwn(value, '__proto__'));
assert.equal(({} as Record<string, unknown>).x, undefined);
const query = analyze({ kind: 'query', source: input, expression: '$.id', jsonc: false });
assert.ok(query.kind === 'query'); assert.equal(query.rows[0].value, huge);
const leaves = analyze({ kind: 'query', source: `{"id":${huge}}`, expression: '$..*', jsonc: false });
assert.equal(leaves.rows.length, 1);
const changed = analyze({ kind: 'diff', source: `{"id":${huge},"n":1.0,"type":1}`, other: '{"type":"1","n":1,"id":18446744073709551614}', jsonc: false });
assert.ok(changed.kind === 'diff');
assert.deepEqual(changed.rows.map(row => row.kind).sort(), ['CHANGE', 'TYPE']);
assert.equal(changed.rows[0].before, huge);
assert.equal(analyze({ kind: 'diff', source: '1e9007199254740992', other: '1e9007199254740993', jsonc: false }).rows.length, 1);
assert.equal(analyze({ kind: 'diff', source: '-0.000e500', other: '0', jsonc: false }).rows.length, 0);
assert.equal(decodeInput(btoa(`{"id":${huge}}`))?.source, `{"id":${huge}}`);
const header = btoa('{"alg":"HS256"}').replace(/=/g, '');
const payload = btoa(`{"id":${huge}}`).replace(/=/g, '');
assert.equal(decodeInput(`${header}.${payload}.signature`)?.kind, 'jwt');
assert.equal(decodeInput(JSON.stringify(`{"id":${huge}}`))?.kind, 'escaped');
assert.equal(decodeInput('not base64 JSON'), null);
assert.equal(decodeInput('"18446744073709551615"'), null);
assert.equal(decodeInput('"true"'), null);
assert.equal(decodeInput('eyJ4IjoxfQ==')?.source, '{"x":1}');
const repaired = repairJson('\uFEFF{\u200Bid:18446744073709551615, name:\'a\', note:"keep\u200Bme", /*comment*/}');
assert.ok(repaired.ok); assert.ok(validate(repaired.source).ok);
assert.ok(repaired.source.includes(huge)); assert.ok(repaired.source.includes('keep\u200Bme'));
const masked = maskJson(`{/*local*/"id":${huge},"email":"a@example.com","phone":"13812345678","card":"4111111111111111","nationalId":"11010519491231002X","ip":"192.168.1.1","v6":"2001:db8::1","password":"abc","note":"hello"}`, { mode: 'jsonc' });
assert.ok(masked.ok); assert.ok(masked.source.includes(huge)); assert.ok(masked.source.includes('/*local*/')); assert.ok(masked.source.includes('"hello"'));
for (const secret of ['a@example.com', '13812345678', '4111111111111111', '11010519491231002X', '192.168.1.1', '2001:db8::1', '"abc"']) assert.ok(!masked.source.includes(secret), secret);
assert.equal(formatPath(['data', 'users', 0, 'id'], 'javascript'), 'res.data.users[0].id');
assert.equal(formatPath(['data', 'users', 0, 'id'], 'jq'), '.data.users[0].id');
assert.equal(formatPath(['a/b', '~key', 0], 'pointer'), '/a~1b/~0key/0');
assert.equal(formatPath(['a b'], 'jq'), '.["a b"]');
const array = '[' + Array.from({ length: BRANCH_PAGE_SIZE + 3 }, (_, index) => `{"id":${index},"nested":[1,2]}`).join(',') + ']';
const page = branch(array, [], 1);
assert.equal(page.total, BRANCH_PAGE_SIZE + 3); assert.equal(page.rows.length, 3); assert.deepEqual(page.rows[0].path, [BRANCH_PAGE_SIZE]);
const nested = branch(array, [BRANCH_PAGE_SIZE, 'nested']);
assert.equal(nested.rows.length, 2); assert.equal(array.slice(nested.rows[1].offset, nested.rows[1].offset + nested.rows[1].length), '2');
assert.deepEqual(discoverArrays('{"items":' + array + '}').map(item => item.path), [['items']]);
const table = largeTable('{"items":' + array + '}', ['items'], 1);
assert.equal(table.total, BRANCH_PAGE_SIZE + 3); assert.equal(table.rows.length, 3); assert.equal(table.rows[0].cells.id, String(BRANCH_PAGE_SIZE));
assert.deepEqual(table.headers, ['id', 'nested']);
const bigGraph = largeGraph(array, 3);
assert.equal(bigGraph.items.length, 300); assert.ok(bigGraph.truncated);
const types = await generateTypes('{"name":"A","nested":{"enabled":true}}', 'typescript', '    ');
assert.ok(types.join('\n').includes('export interface Root'));
assert.ok(types.some(line => line.startsWith('    name')));
for (const target of ['python', 'go', 'rust'] as const) {
  const generated = (await generateTypes('{"name":"A","nested":{"enabled":true}}', target, '    ')).join('\n');
  assert.ok(generated.includes('Root') && generated.includes('name') && generated.includes('enabled'), `${target} output must include the inferred root and nested fields`);
}
const largeText = '{"items":[' + (`{"id":${huge},"text":"value","nested":[]},`).repeat(50000).slice(0, -1) + ']}';
assert.ok(largeText.length > 2_000_000);
for (const indent of ['4', 'tab'] as const) {
  const formatted = beautifyJson(largeText, indent);
  assert.ok(formatted.ok && validate(formatted.source).ok);
  assert.ok(formatted.source.startsWith(indent === '4' ? '{\n    "items": [' : '{\n\t"items": ['));
  assert.equal(minifyJson(formatted.source).source, largeText);
}
const jq = await createRequire(import.meta.url)('jq-web');
const projection = jq.raw(`{"items":[{"id":${huge},"title":"A"}]}`, '.items[] | {id,title}', ['-c']).trim();
assert.equal(projection, `{"id":${huge},"title":"A"}`);
console.log('Lossless numbers, semantic types, smart input, masking, paths, paged branches and real JQ WASM checks passed.');
