import assert from 'node:assert/strict';
import { documentTree, editNode, findObjectArrays, flattenTree, pathAtOffset, pathText, rawSummary, tableHeaders, valueChild } from '../src/lib/json/views';
const strict = { mode: 'strict' as const };
const jsonc = { mode: 'jsonc' as const };
assert.equal(pathText(['data', 'users', 0, 'profile', 'email']), '$.data.users[0].profile.email');
assert.equal(pathText(['a.b', '', 'x"y', 1]), '$["a.b"][""]["x\\"y"][1]');
const source = '{"data":{"users":[{"profile":{"email":"a@b"},"n":900719925474099312345}, {"enabled":true}]}}';
const root = documentTree(source, false)!;
assert.deepEqual(pathAtOffset(root, source.indexOf('email') + 2), ['data', 'users', 0, 'profile', 'email']);
assert.deepEqual(pathAtOffset(root, source.indexOf('a@b') + 1), ['data', 'users', 0, 'profile', 'email']);
const arrays = findObjectArrays(root);
assert.equal(arrays.length, 1);
assert.equal(pathText(arrays[0].path), '$.data.users');
assert.deepEqual(tableHeaders(arrays[0].node).headers, ['profile', 'n', 'enabled']);
assert.equal(tableHeaders(arrays[0].node, 2).truncated, true);
const n = valueChild(arrays[0].node.children![0], 1);
assert.equal(rawSummary(source, n), '900719925474099312345');
const replace = editNode(source, n, 'replace', '900719925474099399999', '', '4', strict);
assert.ok(replace.includes('900719925474099399999'));
assert.ok(replace.includes('\n    "data"'));
const added = editNode(source, arrays[0].node.children![0], 'add', '900719925474099388888', 'big', 'tab', strict);
assert.ok(added.includes('900719925474099312345'));
assert.ok(added.includes('900719925474099388888'));
assert.ok(added.includes('\n\t"data"'));
assert.throws(() => editNode(source, arrays[0].node.children![0], 'add', 'null', 'n', '2', strict));
assert.throws(() => editNode(source, n, 'replace', 'oops', '', '2', strict));
assert.throws(() => editNode(source, root, 'delete', '', '', '2', strict));
const removed = editNode(source, n, 'delete', '', '', '2', strict);
assert.ok(!removed.includes('"n"'));
const commentSource = '{\n // retain\n "big":900719925474099312345, "items":[1,2,],\n}';
const commentTree = documentTree(commentSource, true)!;
const commentAdded = editNode(commentSource, commentTree, 'add', '{"x":900719925474099311111}', 'new', '2', jsonc);
assert.ok(commentAdded.includes('// retain'));
assert.ok(commentAdded.includes('900719925474099312345'));
assert.ok(commentAdded.includes('900719925474099311111'));
const arrayAdded = editNode('[1,2]', documentTree('[1,2]', false)!, 'add', '900719925474099322222', '', '2', strict);
assert.ok(arrayAdded.includes('900719925474099322222'));
const wideSource = JSON.stringify(Array.from({length: 200}, (_, i) => i));
const wide = documentTree(wideSource, false)!;
const flat = flattenTree(wide, new Set([0]), 30);
assert.equal(flat.rows.length, 30);
assert.equal(flat.truncated, true);
assert.equal(flat.rows[1].path[0], 0);
assert.equal(flattenTree(root, new Set()).rows.length, 1);
const duplicates = documentTree('{"x":1,"x":2}', false)!;
assert.equal(duplicates.children!.length, 2);
const nested = documentTree('{"users":[{"orders":[{"id":1}]}]}', false)!;
assert.deepEqual(findObjectArrays(nested).map(row => pathText(row.path)), ['$.users', '$.users[0].orders']);
const expanded = new Set<number>();
function expand(node: typeof root) {
  expanded.add(node.offset);
  if (node.type === 'object' || node.type === 'array') node.children?.forEach((_, index) => expand(valueChild(node, index)));
}
expand(nested);
const all = flattenTree(nested, expanded);
assert.deepEqual(all.rows.map(row => pathText(row.path)), ['$', '$.users', '$.users[0]', '$.users[0].orders', '$.users[0].orders[0]', '$.users[0].orders[0].id']);
assert.equal(flattenTree(nested, expanded, all.rows.length).truncated, false);
assert.equal(flattenTree(nested, expanded, all.rows.length - 1).truncated, true);
for (const indent of ['2', '4', 'tab'] as const) {
  const updated = editNode('{"x":0}', documentTree('{"x":0}', false)!, 'add', '{"list":[1,true,null]}', 'data', indent, strict);
  const prefix = indent === 'tab' ? '\t' : ' '.repeat(Number(indent));
  assert.ok(updated.includes(`\n${prefix}"data"`));
  assert.ok(updated.includes(`\n${prefix.repeat(2)}"list"`));
}
console.log('View paths, lossless editing, table discovery and bounded traversal checks passed.');
